/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_KeyMonitorMethods */

#ifndef _Included_core_KeyMonitorMethods
#define _Included_core_KeyMonitorMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_KeyMonitorMethods
 * Method:    identify
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_core_KeyMonitorMethods_identify
  (JNIEnv *, jobject, jstring);

/*
 * Class:     core_KeyMonitorMethods
 * Method:    grab
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_core_KeyMonitorMethods_grab
  (JNIEnv *, jobject, jstring);

/*
 * Class:     core_KeyMonitorMethods
 * Method:    keyrepeat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_core_KeyMonitorMethods_keyrepeat
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
