/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_ParseXML */

#ifndef _Included_core_ParseXML
#define _Included_core_ParseXML
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_ParseXML
 * Method:    OutputActiveWindow
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_core_ParseXML_OutputActiveWindow
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
